[project]
name = "default"
version = "0.1.0"
description = "RAG to ask questions about Wheel of Time"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "bs4>=0.0.2",
    "ebooklib>=0.18",
    "langchain-text-splitters>=0.3.0",
    "sentence-transformers>=3.2.1",
]
